services:
  app:
    build: .
    container_name: colecifebens-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: colecifebens
      DB_USERNAME: colecifebens
      DB_PASSWORD: admin

  db:
    image: mysql:8
    container_name: colecifebens-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: colecifebens
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

#   db:
#     image: postgres:18
#     container_name: colecifebens-db
#     restart: always
#     environment:
#       POSTGRES_DB: colecifebens
#       POSTGRES_USER: colecifebens
#       POSTGRES_PASSWORD: admin
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql

# volumes:
#   db_data: